---
title: "Gov 50 Final Project"
author: "Isa MarionSims"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Does an individual’s religiousness affect their political ideology (on the spectrum between “left” and “right”)?  I hypothesize that, based on my knowledge of how the American political arena works, those who are more pious will tend more towards right-wing beliefs because the right is often understood as the more conservative party, and several religions espouse conservative practices as part of their belief systems; I am interested in understanding whether this pattern is, as I suspect, not just an American phenomenon.  To test this, I intend to use data from the most recent wave of the World Values Survey, where my unit of analysis will be an individual, and I am also particularly interested in seeing how/if those trends differ across different religions and/or nationalities as a secondary area of exploration.  My explanatory variable of interest is an individual’s self-professed level of religiosity as measured by this question: “Independently of whether you attend religious services or not, would you say you are…?,” where respondents can answer either “1) A religious person,” “2) Not a religious person,” or “3) An atheist.”  My outcome variable of interest is an individual’s self-placement on the spectrum of political ideology as measured by this question: “In political matters, people talk of "the left" and "the right."  How would you place your views on this scale, generally speaking?,” to which respondents code their answers on a scale from 1 to 10 where 1 is “Left” and 10 is “Right.”  The observation that would prove my hypothesis would be if the data suggested that individuals who indicated that they were more religious did in fact trend more towards the right end of the political spectrum; and alternatively, my findings would disprove my hypothesis if I observed a trend that showed that individuals who indicated that they were more religious did not trend more towards the right end of the political spectrum (either because there was a relatively even split or because they actually tended more towards the left).
